### ISSUE TITLE
NDViewer doesn't redraw canvas on successive setData calls

### ISSUE THREAD

**Issue by gselzer** [pyapp-kit/ndv#39]
* ndv version: 0.0.4
* Python version: 3.12.3
* Operating System: Windows 11

### Description

I've been trying to call `NDViewer.setData()` a couple times, with new data. It turns out that I can call `setData` once and the viewer correctly redraws the data, however after that first time the canvas does not update.

From a bit of digging, I've narrowed the bug down to somewhere in `ndv.viewer._dims_slider.py`. The first time `NDViewer.set_current_index` is called from within `NDViewer.set_data`, it causes a redraw [here](https://github.com/pyapp-kit/ndv/blob/b79241c146bcbbb8160925f8cafbe8734ff75cef/src/ndv/viewer/_dims_slider.py#L409) with `self.value() == {0: 256, 1: 256}`. The **second** time it is called, `self.value() == {}`, and the `self.valueChanged` signal is not emitted.

I further have found that, on both calls to `NDViewer.set_data`, `DimsSlider.setValue` is invoked [here](https://github.com/pyapp-kit/ndv/blob/b79241c146bcbbb8160925f8cafbe8734ff75cef/src/ndv/viewer/_dims_slider.py#L277). However, **only on the first invocation** is [`DimsSlider._on_int_value_changed`](https://github.com/pyapp-kit/ndv/blob/b79241c146bcbbb8160925f8cafbe8734ff75cef/src/ndv/viewer/_dims_slider.py#L345) invoked, leading to the dimension being set within the `DimsSliders.value()` on the first `setData` invocation. This is currently as far as I've gotten.

### What I Did

Here's an MCVE. If you click the "Add image" button once, then you'll get an image of all ones. Further clicks to the button should continue to increment the data, however the canvas doesn't show it:
```python
from qtpy.QtCore import QCoreApplication
from qtpy.QtWidgets import QPushButton, QApplication
from ndv import NDViewer
import numpy
import sys


class Example(NDViewer):

    def __init__(self) -> None:
        super().__init__()
        self.save_btn = QPushButton("Add image")
        self.save_btn.clicked.connect(self.add_image)
        self._btns.insertWidget(0, self.save_btn)
        self.i = 0
    
    def add_image(self) -> None:
        data = numpy.ndarray((256, 256))
        data[:, :] = self.i
        self.i = self.i + 1
        self.set_data(data)


## Most of the code below is copied from ndv.util

def _get_app() -> tuple[QCoreApplication, bool]:
    is_ipython = False
    if (app := QApplication.instance()) is None:
        app = QApplication([])
        app.setApplicationName("ndv")
    elif (ipy := sys.modules.get("IPython")) and (shell := ipy.get_ipython()):
        is_ipython = str(shell.active_eventloop).startswith("qt")

    return app, not is_ipython

app, should_exec = _get_app()
viewer = Example()
viewer.show()
viewer.raise_()
if should_exec:
    app.exec()

```

**Comment by gselzer** [comment]
Ach, I'm dumb - `[DimsSlider._on_int_value_changed](https://github.com/pyapp-kit/ndv/blob/b79241c146bcbbb8160925f8cafbe8734ff75cef/src/ndv/viewer/_dims_slider.py#L345)` is only invoked the second time because it *isn't* changing the second time! 🤦 

Anywho, we still need to tell the canvas to update at some point - @tlambert03 do you have any opinions on where we do that?

**Comment by tlambert03** [comment]
This is a good use case, and a definite bug, thanks.  It's an easy fix, but here's the explanation:

As you know, the "typical" update process is to update the canvas when the index changes, either via a change in the sliders, or via `set_current_index`.  However, if the data is changing without changing the position of the sliders, that's just not a user case we've explicitly prepared for.  (it's an obvious use case of course, but with pymmcore, when the data changed, we *also* triggered a change in index).

The way to force a draw without going through the change of index mechanism is  `viewer._update_data_for_index(...)` ... so if we want to force a redraw without changing the index, it would be `self._update_data_for_index(self._dims_sliders.value())`.  You'll find that exact code called a couple places (such as in set_ndim, and set_channel_mode).  So it would a be a very reasonable thing to add in set_data as well.  I'll make a public `refresh()` method and call it in set_data
